### ISSUE TITLE
AmpliconAnalysisTyping.py fails

### ISSUE THREAD

**Issue by pb-jlandolin** [bnbowman/HlaTools#1]
Cross posting Michael's problem in the correct repository.

 I installed HlaTools from github and I got it working on several datasets (AmpliconAnalysisTyping.py). I was trying to update the sequences in pbhla/data/Class_I, by replacing each file in A, B, C and H with the latest versions I got. The problem is, the AmpliconAnalysisTyping.py now fails. 

When I run the analysis, the following files are generated: amplicon_analysis.all.fastq, amplicon_analysis.all.md5, amplicon_analysis.all.oriented.fastq and amplicon_analysis.all.oriented.selected.fastq. The amplicon_analysis.all.oriented.selected.fastq file is empty. I have attached the log file. 

Do you have any suggestions on what might be causing the problem? Let me know if you need any other details. 

Kind regards, 

Michael. 

2014-08-07 15:44:34 [INFO - data] Using existing Exon Reference fofn
2014-08-07 15:44:34 [INFO - data] Using existing Genomic Reference fasta
2014-08-07 15:44:34 [INFO - data] Using existing cDNA Reference fasta
2014-08-07 15:44:34 [INFO - input] Input appears to be a directory, looking for sequence files
2014-08-07 15:44:34 [INFO - input] Chimera/Noise sequence file detected, combining with primary output
2014-08-07 15:44:34 [INFO - utils] Aligning ../A01_1-1408051407254857_BC1/amplicon_analysis.all.fastq sequences to 453 references
2014-08-07 15:44:36 [INFO - orientation] Reorienting all sequences in ../A01_1-1408051407254857_BC1/amplicon_analysis.all.fastq to the direction of their reference
2014-08-07 15:44:36 [INFO - orientation] Identified 0 sequences needing Reverse Complementation
2014-08-07 15:44:36 [INFO - orientation] Writing out sequences to ../A01_1-1408051407254857_BC1/amplicon_analysis.all.oriented.fastq
2014-08-07 15:44:36 [INFO - extract] Sorting sequences for selection according to "accuracy"
2014-08-07 15:44:36 [INFO - extract] Selecting top sequences from ../A01_1-1408051407254857_BC1/amplicon_analysis.all.oriented.fastq according to the "both" policy
2014-08-07 15:44:36 [INFO - extract] Selected 0 sequences from 3 total for further analysis
2014-08-07 15:44:36 [INFO - extract] Writing the selected sequences out to ../A01_1-1408051407254857_BC1/amplicon_analysis.all.oriented.selected.fastq
2014-08-07 15:44:36 [ERROR - utils] Expected output file not found! "../A01_1-1408051407254857_BC1/amplicon_analysis.all.oriented.selected.fastq"

**Comment by WenchaoLin** [comment]
How to start the analysis? I just run with
`#AmpliconAnalysisTyping.py in.fasta `

error occured with:
```
2015-12-25 08:50:49 [INFO - data] Using existing Exon Reference fofn
2015-12-25 08:50:49 [INFO - data] Using existing Genomic Reference fasta
2015-12-25 08:50:49 [INFO - data] Using existing cDNA Reference fasta
2015-12-25 08:50:49 [INFO - input] Input appears to be a valid Fasta file
2015-12-25 08:50:49 [INFO - utils] Aligning in.fasta sequences to 654 references
2015-12-25 08:50:51 [INFO - orientation] Reorienting all sequences in in.fasta to the direction of their reference
2015-12-25 08:50:51 [INFO - orientation] Identified 0 sequences needing Reverse Complementation
2015-12-25 08:50:51 [INFO - orientation] Writing out sequences to in.oriented.fasta
Traceback (most recent call last):
  File "/work/lwc/workFlow/hla_env/bin/AmpliconAnalysisTyping.py", line 4, in <module>
    __import__('pkg_resources').run_script('HlaTools==0.4.1', 'AmpliconAnalysisTyping.py')
  File "/work/lwc/workFlow/hla_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/work/lwc/workFlow/hla_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/work/lwc/workFlow/hla_env/lib/python2.7/site-packages/HlaTools-0.4.1-py2.7.egg/EGG-INFO/scripts/AmpliconAnalysisTyping.py", line 31, in <module>
    debug=args.debug )
  File "/work/lwc/workFlow/hla_env/lib/python2.7/site-packages/HlaTools-0.4.1-py2.7.egg/pbhla/typing/sequences.py", line 50, in type_sequences
    loci=loci)
  File "/work/lwc/workFlow/hla_env/lib/python2.7/site-packages/HlaTools-0.4.1-py2.7.egg/pbhla/alleles/extract.py", line 59, in extract_alleles
    assert get_file_type(input_file) == 'fastq'
AssertionError
```
